id: P001704
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 10:15:39.945497
source_metadata:
  id: bdr:W1KG25867
  title: མཚོ་གཏིང་གི་ལེ་དབར་ཉི་ཁྲི།
  author: ''
  volumes:
    b56c8b7165e743ac9c3740ffca65bdb4:
      image_group_id: I1KG25869
      title: ''
      volume_number: 1
      total_pages: 238
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
