id: P001704
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG25867
  title: མཚོ་གཏིང་གི་ལེ་དབར་ཉི་ཁྲི།
  author: ''
  volumes:
    b56c8b7165e743ac9c3740ffca65bdb4:
      image_group_id: I1KG25869
      title: ''
      volume_number: 1
      total_pages: 238
      base_file: v001.txt
